---
root: true
parser: "@typescript-eslint/parser"
plugins: ["@typescript-eslint"]
extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended"]
rules:
  no-console: error
  "@typescript-eslint/no-non-null-assertion": off
ignorePatterns:
  - src/types
  - src/financial-dash
