repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        args: [--fix]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@4.31.2"
          - "@typescript-eslint/parser@4.31.2"
          - "eslint@7.32.0"
          - "typescript@4.4.3"
