enableGlobalCache: true
yarnPath: .yarn/releases/yarn-3.0.2.cjs

packageExtensions:
  "pino@*":
    peerDependencies:
      "pino-pretty": "^7.0.0"
    peerDependenciesMeta:
      pino-pretty:
        optional: true
