enableGlobalCache: true

packageExtensions:
  "pino@*":
    peerDependencies:
      "pino-pretty": "^7.0.0"
    peerDependenciesMeta:
      pino-pretty:
        optional: true

yarnPath: .yarn/releases/yarn-2.4.3.cjs
