/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/transactions": {
    get: operations["getTransactions"];
    parameters: {};
  };
  "/api/usage": {
    get: operations["getUsage"];
    parameters: {};
  };
}

export interface components {
  schemas: {
    LauntelTransactionResponse: {
      perMonth: string;
    };
    UsageResponse: {
      usage: { [key: string]: unknown };
    };
  };
  responses: {};
  parameters: {};
  requestBodies: {};
  headers: {};
}

export interface operations {
  getTransactions: {
    parameters: {};
    responses: {
      /** Ok */
      default: {
        content: {
          "application/json": components["schemas"]["LauntelTransactionResponse"];
        };
      };
    };
  };
  getUsage: {
    parameters: {};
    responses: {
      /** Ok */
      default: {
        content: {
          "application/json": components["schemas"]["UsageResponse"];
        };
      };
    };
  };
}

export interface external {}
