/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/up": {
    get: operations["getUp"];
    parameters: {};
  };
}

export interface components {
  schemas: {
    UpAttributes: {
      description: string;
      message: string;
      createdAt: string | string;
      amount: unknown;
    };
    UpTransaction: {
      id: string;
      attributes: components["schemas"]["UpAttributes"];
    };
    UpLinks: {
      /** Format: url */
      next?: string;
    };
    UpTransactionResponse: {
      items: components["schemas"]["Array"][];
      links: components["schemas"]["UpLinks"];
    };
    Amount: {
      valueInBaseUnits: number;
      value: string;
    };
  };
  responses: {};
  parameters: {};
  requestBodies: {};
  headers: {};
}

export interface operations {
  getUp: {
    parameters: {};
    responses: {
      /** Ok */
      default: {
        content: {
          "application/json": components["schemas"]["UpTransactionResponse"];
        };
      };
    };
  };
}

export interface external {}
