/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/invoice": {
    post: operations["createInvoice"];
  };
  "/api/invoice/{invoiceId}": {
    get: operations["getInvoice"];
    put: operations["updateInvoice"];
    parameters: {
      path: {
        invoiceId: string;
      };
    };
  };
}

export interface components {
  schemas: {
    InvoiceResponse: {
      clientId: string;
      amount: number;
      id: string;
    };
    PartialInvoiceRequest: {
      clientId?: string;
      amount?: number;
    };
    CreateInvoiceRequest: components["schemas"]["PartialInvoiceRequest"] &
      ({ [key: string]: unknown } & {
        clientId: unknown;
        amount: unknown;
      });
    CreateInvoiceResponse: {
      data: {
        id: string;
      };
    };
  };
}

export interface operations {
  createInvoice: {
    responses: {
      /** OK */
      default: {
        content: {
          "application/json": components["schemas"]["CreateInvoiceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInvoiceRequest"];
      };
    };
  };
  getInvoice: {
    parameters: {
      path: {
        invoiceId: string;
      };
    };
    responses: {
      /** OK */
      default: {
        content: {
          "application/json": components["schemas"]["InvoiceResponse"];
        };
      };
    };
  };
  updateInvoice: {
    parameters: {
      path: {
        invoiceId: string;
      };
    };
    responses: {
      /** OK */
      default: {
        content: {
          "application/json": components["schemas"]["CreateInvoiceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PartialInvoiceRequest"];
      };
    };
  };
}

export interface external {}
