/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/invoice": {
    post: operations["createInvoice"];
  };
}

export interface components {
  schemas: {
    CreateInvoiceRequest: {
      clientId: string;
      amount: number;
    };
    CreateInvoiceResponse: {
      id: string;
    };
  };
}

export interface operations {
  createInvoice: {
    responses: {
      /** OK */
      default: {
        content: {
          "application/json": components["schemas"]["CreateInvoiceResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInvoiceRequest"];
      };
    };
  };
}

export interface external {}
