openapi: 3.0.1
info:
  title: Financial Dash
  version: 0.0.1
components:
  securitySchemes:
    Jwt:
      type: http
      scheme: bearer
      bearerFormat: jwt
security:
  - Jwt: []
servers:
  - url: https://financial-dash.vc.mause.me
