openapi: 3.0.1
info:
  title: Financial Dash
paths:
  /api/invoice:
    post:
      operationId: createInvoice
      parameters:
        - name: clientId
          type: string
        - name: amount
          type: number
      responses:
        200:
          description: OK
          content:
            application/json:
              type: object
              properties:
                id:
                  type: string
