openapi: 3.0.1
info:
  title: Financial Dash
paths:
  /api/invoice:
    post:
      operationId: createInvoice
      requestBody:
        - name: clientId
          type: string
        - name: amount
          type: number
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
