openapi: 3.0.1
info:
  title: Financial Dash
  version: 0.0.1
components:
  securitySchemes:
    Jwt:
      type: http
      scheme: bearer
      bearerFormat: jwt
  schemas:
    CreateInvoiceRequest:
      type: object
      required: [clientId, amount]
      properties:
        clientId:
          type: string
        amount:
          type: number
    CreateInvoiceResponse:
      type: object
      required: [id]
      properties:
        id:
          type: string
security:
  - Jwt: []
servers:
  - url: https://financial-dash.vercel.app
paths:
  /api/invoice:
    post:
      operationId: createInvoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              ref: "#/components/schemas/CreateInvoiceRequest"
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                ref: "#/components/schemas/CreateInvoiceResponse"
