openapi: 3.0.1
info:
  title: Financial Dash
  version: 0.0.1
components:
  securitySchemes:
    Jwt:
      type: http
      scheme: bearer
      bearerFormat: jwt
  schemas:
    InvoiceResponse:
      type: object
      required: [clientId, amount, id]
      properties:
        clientId:
          type: string
        amount:
          type: number
        id:
          type: string
    CreateInvoiceRequest:
      type: object
      required: [clientId, amount]
      properties:
        clientId:
          type: string
        amount:
          type: number
    CreateInvoiceResponse:
      type: object
      required: [data]
      properties:
        data:
          type: object
          required: [id]
          properties:
            id:
              type: string
    Empty:
      type: object
security:
  - Jwt: []
servers:
  - url: https://financial-dash.vercel.app
paths:
  /api/invoice:
    post:
      operationId: createInvoice
      tags: [invoice]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateInvoiceRequest"
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateInvoiceResponse"
  /api/invoice/{invoiceId}:
    parameters:
      - name: invoiceId
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getInvoice
      tags: [invoice]
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvoiceResponse"
    put:
      operationId: updateInvoice
      tags: [invoice]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/CreateInvoiceRequest"
                - $ref: "#/components/schemas/Empty"
      responses:
        default:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateInvoiceResponse"
