on: push

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 14
          cache: yarn
      - run: yarn --frozen
      - name: TypeScript Error Reporter
        uses: andoshin11/typescript-error-reporter-action@v1.0.3
      - run: yarn workspaces run build
      - run: yarn test
      - run: yarn api_tests
        timeout-minutes: 2
