on: push

name: Typecheck
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - run: yarn --frozen
      - name: Typescript compiler
        uses: iCrawl/action-tsc@v1
      - run: yarn test
