on: push

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18
          cache: yarn
      - run: yarn
      - run: yarn workspaces foreach --all run build
      - run: yarn test
      - run: yarn api_tests
        timeout-minutes: 2
