on: push

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - run: yarn --frozen
      - name: TypeScript Error Reporter
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
      - run: yarn test
      - run: ../node_modules/.bin/jest
        working-directory: api_tests/
        timeout-minutes: 2
      - run: yarn run vercel-openapi generate .  --inputFile public/openapi.yaml
        env:
          JWT_SECRET: secret
          TS_NODE_COMPILER_OPTIONS: |
            {"module": "commonjs" }
