on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}

name: Update types
jobs:
  update_types:
    name: Update types
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: supabase
            url: https://jgoewtofthnufcvpvglq.supabase.co/rest/v1/
          - name: invoice-ninja
            url: https://app.swaggerhub.com/apiproxy/registry/invoiceninja/invoiceninja/5.3
          - name: launtel
            url: https://launtel.vercel.app/api/openapi.yaml

    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Update types
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            npx openapi-typescript ${{ matrix.url }}?apikey=${{ secrets.SUPABASE_KEY }} --output src/${{ matrix.name }}.ts
          COMMIT_MESSAGE: "chore: update ${{ matrix.name }} types"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore-${{ matrix.name }}-update-${PR_ID}"
          PR_TITLE: "chore: update ${{ matrix.name }} types"
